# 0. namespace 생성
apiVersion: v1
kind: Namespace
metadata:
  name: autocomplete
---

# 데이터 영구 저장을 위한 PVC 설정
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minio-pvc
  namespace: autocomplete
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi # 모델 크기에 맞춰
---

# 1. MinIO 배포 (Deployment)
apiVersion: apps/v1
kind: Deployment
metadata:
  name: minio
  namespace: autocomplete # 동일 ns
spec:
  replicas: 1
  selector:
    matchLabels:
      app: minio
  template:
    metadata:
      labels:
        app: minio
    spec:
      volumes:
        - name: minio-storage
          persistentVolumeClaim:
            claimName: minio-pvc
      containers:
        - name: minio
          image: minio/minio:latest
          args:
            - server
            - /data
            - --console-address
            - :9001
          env:
            # 실제 운영 시에는 Secret으로 관리
            - name: MINIO_ROOT_USER
              value: "minioadmin"
            - name: MINIO_ROOT_PASSWORD
              value: "minioadmin"
          ports:
            - containerPort: 9000 # API 포트
            - containerPort: 9001 # 웹 콘솔 포트
          volumeMounts:
            - name: minio-storage
              mountPath: /data
---
# 2. MinIO 서비스 (Service)
apiVersion: v1
kind: Service
metadata:
  name: minio-service
  namespace: autocomplete
spec:
  type: NodePort # 외부에서 웹 콘솔 접속을 위해 NodePort 사용 (또는 Ingress)
  ports:
    - port: 9000
      targetPort: 9000
      name: api
    - port: 9001
      targetPort: 9001
      name: console
      nodePort: 30090 # 웹 콘솔 접속용 (http://localhost:30090)
  selector:
    app: minio
---

apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minio-ingress
  namespace: autocomplete
  annotations:
    # 업데이터 용량 제한 해제
    nginx.ingress.kubernetes.io/proxy-body-size: "0"
spec:
  ingressClassName: nginx
  rules:
    - host: "minio.autocomplete-api.local"
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: minio-service
                port:
                  number: 9001