{{- if .Values.relkey.enabled}}}

### Inference Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.relkey.inference.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.relkey.inference.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.relkey.inference.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.relkey.inference.name }}
    spec:
      containers:
        - name: inference-container
          image: {{ .Values.relkey.inference.image }}
          imagePullPolicy: Always
          ports:
            - containerPort: {{ .Values.relkey.inference.port }}

          # 모델 로딩이 정상 동작했는지 확인 (성공 전까지 트래픽 차단)
          readinessProbe:
            httpGet:
              path: /health
              port: {{ .Values.relkey.inference.port }}
            initialDelaySeconds: 60   # 컨테이너 시작 후 30초 뒤부터 체크
            periodSeconds: 10         # 10초 간격으로 체크
            failureThreshold: 10      # 30번 실패시 모델 로딩 실패로 간주
          resources:
{{ toYaml .Values.relkey.inference.resources | indent 12 }}
---
### Inference Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.relkey.inference.name }}-svc
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.relkey.inference.name }}
  ports:
    - protocol: TCP
      port: 80
      targetPort: {{ .Values.relkey.inference.port }}
---
### API Deployment
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.relkey.api.name }}
  namespace: {{ .Values.namespace }}
spec:
  replicas: {{ .Values.relkey.api.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.relkey.api.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.relkey.api.name }}
    spec:
      containers:
        - name: api-container
          image: {{ .Values.relkey.api.image }}
          env:
            - name: INFERENCE_URL
              value: "http://{{ .Values.relkey.inference.name }}-svc.{{ .Values.namespace }}.svc.cluster.local/generate"
          ports:
            - containerPort: {{ .Values.relkey.api.port }}
          resources:
{{ toYaml .Values.relkey.api.resources | indent 12 }}
---
### API Service
apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.relkey.api.name }}
  namespace: {{ .Values.namespace }}
spec:
  type: ClusterIP
  selector:
    app: {{ .Values.relkey.api.name }}
  ports:
    - port: 80
      targetPort: {{ .Values.relkey.api.port }}

{{- end}}}